config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root to: 'products#show'

  get 'products/show'

  get 'products/setup'
  post 'products/setup'

  post 'products/upload'

  post 'products/update'

  get 'products/check'

  get 'products/report'

  get 'products/reset'

  delete 'products/delete'
  mount Resque::Server.new, at: "/resque"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/sign_in' => 'devise/sessions#new'
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  require 'peddler'
  require 'date'
  require 'csv'

  def crawl(user)
    #MWSにアクセス
    logger.debug('======= CRAWL START =========')
    mp = "A1VC38T7YXB528"
    temp = Account.find_by(user: user)
    sid = temp.seller_id
    skey = temp.secret_key
    awskey = temp.aws_key
    border = temp.stock_border
    apitoken = temp.cw_api_token
    roomid = temp.cw_room_id
    roomid2 = temp.cw_room_id2
    ids = temp.cw_ids

    logger.debug('======= VALUE SET =========')

    tt = Product.where(user: user)

    tt.update(jriden: false, riden: false)

    #asinlist = tt.pluck(:asin)
    asinlist = tt.pluck(:sku)
    client = MWS.products(
      primary_marketplace_id: mp,
      merchant_id: sid,
      aws_access_key_id: awskey,
      aws_secret_access_key: skey
    )

    asins = []
    logger.debug('======= VALUE SET END =========')
    j = 0

    logger.debug(asinlist)
    i = 0
    asinlist.each do |taisn|
      logger.debug(i)
      asins.push(taisn)
      if j == 9 || i == asinlist.length-1 then
        asins.slice!(j, 9 - asins.length)

        logger.debug('======= ASIN =========')
        logger.debug(asins)
        logger.debug('======= ASIN END =========')

        response = client.get_lowest_offer_listings_for_sku(asins,{item_condition:"New", exclude_me: "false"})
        response2 = client.get_lowest_offer_listings_for_sku(asins,{item_condition:"New", exclude_me: "true"})
        parser = response.parse
        parser2 = response2.parse
        uhash = {}
        parser.each do |product|
          asin = product.dig('Product', 'Identifiers', 'MarketplaceASIN', 'ASIN')
          sku = product.dig('Product', 'Identifiers', 'SKUIdentifier', 'SellerSKU')
          tprice = 0
          buf = product.dig('Product', 'LowestOfferListings', 'LowestOfferListing')
          buf1 = product.dig('Product', 'LowestOfferListings')
          tnum = 0
          if buf1 != nil then
            #出品アリ
            if buf.class == Array then
              #複数出品
              ch1 = false
              ch2 = false
              buf.each do |ttt, k|
                if ttt.dig('Qualifiers', 'FulfillmentChannel') == 'Amazon' then
                  ch1 = true
                elsif ttt.dig('Qualifiers', 'FulfillmentChannel') == 'Merchant' then
                  ch2 = true
                end
                tnum = tnum + ttt.dig('NumberOfOfferListingsConsidered').to_i
              end
              tprice =  buf[0].dig('Price', 'LandedPrice', 'Amount').to_i
            else
              tprice =  buf.dig('Price', 'LandedPrice', 'Amount').to_i
            end
          end
          if sku != nil then
            uhash[sku] = {asin: asin, sku:sku}
            th = uhash[sku]
            if ch1 == false || ch2 == false then
              tnum = 0
            end
            th[:snum] = tnum
            th[:price] = tprice
            uhash[sku] = th
          end
        end

        parser2.each do |product|
          asin = product.dig('Product', 'Identifiers', 'MarketplaceASIN', 'ASIN')
          sku = product.dig('Product', 'Identifiers', 'SKUIdentifier', 'SellerSKU')
          buf = product.dig('Product', 'LowestOfferListings', 'LowestOfferListing')
          buf1 = product.dig('Product', 'LowestOfferListings')
          tnum = 0
          if buf1 != nil then
            #出品アリ

            if buf.class == Array then
              #複数出品
              buf.each do |ttt|
                if ttt.dig('Qualifiers', 'ItemCondition') == "New" then
                  tnum = tnum + ttt.dig('NumberOfOfferListingsConsidered').to_i
                end
              end
            else
              if buf.dig('Qualifiers', 'ItemCondition') == "New" then
                tnum = buf.dig('NumberOfOfferListingsConsidered').to_i
              end
            end
          else
            tnum = 0
          end
          if sku != nil then
            th = uhash[sku]
            th[:rnum] = tnum
            uhash[sku] = th
          end
        end

        logger.debug('======= HASH =========')
        logger.debug(uhash)
        logger.debug('======= HASH END =========')

        uhash.each do |ss|
          logger.debug('======= Info Start =========')
          t_asin = ss[1][:asin]
          t_sku = ss[1][:sku]
          t_price = ss[1][:price]
          t_snum = ss[1][:snum]
          t_rnum = ss[1][:rnum]
          logger.debug(t_asin)
          logger.debug(t_sku)
          logger.debug(t_price)
          logger.debug(t_snum)
          logger.debug(t_rnum)
          logger.debug('======= Info END =========')
          temps = tt.find_by(sku: t_sku)
          #temps = tt.where(asin: t_asin)
          if temps == nil then break end
          if t_snum > 0 then
            logger.debug('======= 自社相乗り =========')
            temps.update(jriden: true)
            msg = "注意!: 自社相乗り \n" + "ASIN: " + t_asin + "\n" + "URL: https://www.amazon.co.jp/dp/" + t_asin
          else
            temps.update(jriden: false)
          end
          if t_rnum > 0 then
            logger.debug('======= 他社相乗り =========')
            temps.update(riden: true, jriden: false)
            msg = "【警告!!】: 他社相乗り \n" + "ASIN: " + t_asin + "\n" + "URL: https://www.amazon.co.jp/dp/" + t_asin
          else
            temps.update(riden: false)
          end
          if t_price > 0 then
            temps.update(price: t_price)
          end

          #通知の条件
          #1. 相乗りがあり
          #2. チェックがなし

          if t_snum > 0 || t_rnum > 0 then
            if temps.checked != true then
              logger.debug(t_snum)
              logger.debug(t_rnum)
              if t_snum > 0 && t_rnum == 0 then
                logger.debug('======= 相乗りあり! =========')
                #   自社相乗り
                #3. FBA在庫があり(0でない)
                #4. ボーダーより多い
                if temps.fba_stock != nil then
                  if temps.fba_stock > border then
                    logger.debug("==== Alert ====")
                    stask(msg, apitoken,roomid, ids)

                    #通知後にチェック
                    t_asin = temps.asin
                    ttt = tt.where(asin: t_asin)
                    ttt.update(checked: true)

                  end
                end
              else
                #   他社相乗り
                #無条件
                logger.debug('======= 相乗りあり　他社相乗り =========')
                stask(msg, apitoken,roomid2, ids)
              end
            end
          end
        end

        asins = []
        j = 0
      else
        j += 1
      end
      i += 1
    end
  end

  #FBA在庫数の確認
  def fba_check(user)
    logger.debug("\n===== Start FBA check =====")
    mp = "A1VC38T7YXB528"
    temp = Account.find_by(user: user)
    sid = temp.seller_id
    skey = temp.secret_key
    awskey = temp.aws_key
    products = Product.where(user:user)

    dt = DateTime.now.gmtime
    endate = dt.yesterday.beginning_of_day.ago(9.hours).iso8601
    stdate = dt.yesterday.beginning_of_day.ago(9.hours).iso8601

    report_type = "_GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA_"
    mws_options = {
      start_date: stdate,
      end_date: endate
    }
    logger.debug(mws_options)
    client = MWS.reports(
      primary_marketplace_id: mp,
      merchant_id: sid,
      aws_access_key_id: awskey,
      aws_secret_access_key: skey
    )

    response = client.request_report(report_type, mws_options)
    parser = response.parse
    reqid = parser.dig('ReportRequestInfo', 'ReportRequestId')

    mws_options = {
      report_request_id_list: reqid,
    }
    process = ""
    logger.debug(reqid)
    while process != "_DONE_" && process != "_DONE_NO_DATA_"
      response = client.get_report_request_list(mws_options)
      parser = response.parse
      process = parser.dig('ReportRequestInfo', 'ReportProcessingStatus')
      logger.debug(process)
      if process == "_DONE_" then
        genid = parser.dig('ReportRequestInfo', 'GeneratedReportId')
        break
      elsif process == "_DONE_NO_DATA_" then
        genid = "NODATA"
        break
      end
      sleep(30)
    end

    logger.debug("====== generated id =======")
    logger.debug(genid)

    if genid.to_s != "NODATA" then
      response = client.get_report(genid)
      parser = response.parse
      logger.debug("====== report data is ok =======\n")
      parser.each do |row|
        if row[6] == 'SELLABLE' then
          tsku = row[2]
          quantity = row[4]
          t1 = products.find_by(sku: tsku)
          if t1 != nil then
            t1.update(fba_stock: quantity)
          end
          logger.debug("SKU: " + tsku + " ,FBA stock: " + quantity.to_s)
        end
      end
    end
    logger.debug("\n===== End FBA check =====\n")
  end

  def msend(message, api_token, room_id)
    base_url = "https://api.chatwork.com/v2"
    endpoint = base_url + "/rooms/" + room_id  + "/messages"
    request = Typhoeus::Request.new(
      endpoint,
      method: :post,
      params: { body: message },
      headers: {'X-ChatWorkToken'=> api_token}
    )
    request.run
    res = request.response.body
    logger.debug(res)
  end

  def stask(message, api_token, room_id, to_ids)
    base_url = "https://api.chatwork.com/v2"
    endpoint = base_url + "/rooms/" + room_id  + "/tasks"
    request = Typhoeus::Request.new(
      endpoint,
      method: :post,
      params: { body: message, to_ids: to_ids },
      headers: {'X-ChatWorkToken'=> api_token}
    )
    request.run
    res = request.response.body
    logger.debug(res)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  require 'nokogiri'
  require 'uri'
  require 'csv'
  require 'peddler'
  require 'typhoeus'
  require 'date'
  require 'kconv'
  require 'rubyXL'

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def show
    @login_user = current_user
    #temp = Product.find_or_create_by(user:current_user.email)
    @products = Product.where(user:current_user.email)
  end

  def delete
    Product.delete_all
    redirect_to root_url
  end

  def check
    if params[:commit] == "監視開始" then
      #temp = Product.new
      #temp.crawl(current_user.email)
      RiderCheckJob.perform_later(current_user.email)
    end
    redirect_to products_show_path
  end

  def update
    tag = params[:chk]
    if tag != nil then
      products = Product.where(user:current_user.email)
      logger.debug(tag)
      tag.each do |tasin|
        logger.debug(tasin)
        tm = products.where(asin: tasin)
        if tm != nil then
          tm.update(checked: true)
        end
      end
    end
    redirect_to products_show_path
  end

  def setup
    @login_user = current_user
    @account = Account.find_or_create_by(user:current_user.email)
    if request.post? then
      @account.update(user_params)
    end
  end

  def report
    user = current_user.email
    GetReportJob.perform_later(user)
    redirect_to products_show_path
  end

  def upload
    if request.post? then
      data = params[:file]
      if data != nil then
        workbook = RubyXL::Parser.parse(data.path)
        worksheet = workbook.first
        #list = CSV.read(data.path, {headers:true, encoding:'Windows_31J:UTF-8'})
        temp = Product.where(user:current_user.email)
        #list.each do |row|
        worksheet.each_with_index do |row, i|
          if i != 0 then
            logger.debug("SKU: " + row[0].to_s + " , ASIN: " + row[1].to_s)
            temp2 = temp.find_or_create_by(asin:row[1].value.to_s, sku:row[0].value.to_s)
          end
        end
      end
    end
    redirect_to products_show_path
  end

  def reset
    temp = Product.where(user:current_user.email)
    temp.update(checked: false)
    redirect_to products_show_path
  end

  private
  def user_params
     params.require(:account).permit(:user, :seller_id, :aws_key, :secret_key, :stock_border, :cw_api_token, :cw_room_id, :cw_room_id2, :cw_ids)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/setup.html.erb
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-10 col-md-10">
      <h2>ツールの設定</h2>
      <div class="col-lg-7">
        <%= form_for(@account, {url: products_setup_path, method: 'post'}) do |f| %>
          <p class="lead">MWSアカウントの設定</p>
          <div class="form-group">
            <%= f.label :seller_id, "セラーID" %>
            <%= f.text_field :seller_id, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :aws_key, "AWSキー" %>
            <%= f.text_field :aws_key, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :secret_key, "秘密キー" %>
            <%= f.text_field :secret_key, class: 'form-control' %>
          </div>
          <p class="lead">通知条件の設定</p>
          <div class="form-group">
            <%= f.label :stock_border, "FBA在庫閾値（この在庫数以下の場合は通知しない）" %>
            <%= f.text_field :stock_border, class: 'form-control' %>
          </div>
          <br>
          <p class="lead">チャットワーク連携設定</p>
          <div class="form-group">
            <%= f.label :cw_api_token, "APIトークン" %>
            <%= f.text_field :cw_api_token, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :cw_room_id, "自社相乗りルームID" %>
            <%= f.text_field :cw_room_id, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :cw_room_id2, "他社相乗りルームID" %>
            <%= f.text_field :cw_room_id2, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :cw_ids, "担当者ID" %>
            <%= f.text_field :cw_ids, class: 'form-control' %>
          </div>
          <div class="actions">
            <%= f.submit "設定する", {id: "setup_btn", onClick: 'alert("更新しました")'} %>
          </div>
        <% end %>
        <br>
        <%= form_tag('/products/reset', method:'get') do %>
          <div class="form-group">
            <%= submit_tag 'チェックのリセット', class:'btn btn-primary' %>
          </div>
        <% end %>
        <br>
        <br>
        <p class="lead">ASINの削除</p>
        <%= link_to 'ASIN全削除', '/products/delete', method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class:'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-10 col-md-10">
      <h2>ASINの読込 & 手動監視実行</h2>
      <%= form_tag('/products/upload', method:'post', multipart: true) do %>
        <div class="form-group">
          <div class="form-inline" id="asin_form" >
            <%= submit_tag '読込', class:'btn btn-primary' %>&nbsp;&nbsp;&nbsp;
            <div class="form-group" style="width: 320px">
              <%= file_field_tag :file %>
            </div>
          </div>
        </div>
      <% end %>

      <%= form_tag('/products/check', method:'get') do %>
        <div class="form-group">
          <%= submit_tag '監視開始', class:'btn btn-primary' %>
        </div>
      <% end %>

      <%= form_tag('/products/update', method:'post') do %>
      <div class="form-group">
        <%= submit_tag '確認状況の更新', class:'btn btn-primary' %>
      </div>

      <table class="table table-striped table-hover table-bordered table-headerfixed ellipsis tablesorter" id="result_table">
        <thead class="thead-inverse" style="font-size: 10pt;">
          <tr>
            <th width="15%">ASIN</th>
            <th width="24%">SKU</th>
            <th width="10%">価格</th>
            <th width="13%">FBA在庫数</th>
            <th width="15%">他社相乗り？</th>
            <th width="15%">自社相乗り？</th>
            <th width="8%">確認</th>
          </tr>
        </thead>
        <% if @products != nil then %>
        <% counter = 0 %>
        <% ahash = Hash.new %>
        <tbody style="font-size: 9pt;">
          <% for temp in @products %>
          <% if temp.checked == true then checked = 'checked="checked"' else checked = "" end %>
          <% if ahash.has_key?(temp.asin) == false then ahash[temp.asin] = 1 %>
          <tr>
            <td width="15%"><a href="https://www.amazon.co.jp/dp/<%= temp.asin %>" target="blank"><%= temp.asin %></a></td>
            <td width="24%"><%= temp.sku %></td>
            <td width="10%"><%= temp.price %></td>
            <td width="13%"><%= if temp.fba_stock != nil then temp.fba_stock else 0 end %></td>
            <td width="15%"><% if temp.riden == true then %>他社相乗りあり<% else %>問題なし<% end %></td>
            <td width="15%"><% if temp.jriden == true then %>自社相乗りあり<% else %>問題なし<% end %></td>
            <td width="8%"><input type="checkbox" name="chk[<%= temp.asin %>]" value="<%= temp.checked %>" <%= checked %> id="chk_<%= temp.asin %>" style="margin-top: 5px;" /></td>
          </tr>
          <% end %>
          <% end %>
        </tbody>
        <% end %>
      </table>
      <% end %>
    </div>
  </div>
</div>


<script type="text/javascript">

  $(document).ready(function()
    {

      $("#result_table").tablesorter();

      $(function() {
        $('[id^="chk"]').click(function(event){
          event.stopPropagation();
        });
        $('[id^="chk"]').parent('td').click(function(event){
          $(this).children('[id^="chk"]').trigger('click');
        });
        $('label[for^="chk"]').click(function(event) {
          event.preventDefault();
        });
      });

    }
  );
</script>